/*await page.goto('https://practicesoftwaretesting.com/');
await expect(page.locator('[data-test="nav-sign-in"]')).toBeVisible();
await expect(page.locator('[data-test="language-select"]')).toBeVisible();
await expect(page.getByText('This is a DEMO application (')).toBeVisible();

await page.locator('[data-test="nav-home"]').click();
await page.locator('[data-test="nav-contact"]').click();
await page.locator('[data-test="language-select"]').click();

await page.getByRole('heading', { name: 'Contact' }).click();
await page.locator('[data-test="first-name"]').click();
await page.locator('[data-test="last-name"]').click();
await page.locator('[data-test="subject"]').selectOption('customer-service');
await page.locator('[data-test="subject"]').selectOption('webmaster');
await page.locator('[data-test="subject"]').selectOption('return');
await page.locator('[data-test="subject"]').selectOption('payments');
await page.locator('[data-test="subject"]').selectOption('warranty');
await page.locator('[data-test="subject"]').selectOption('status-of-order');
await page.locator('[data-test="message"]').click();
await page.locator('[data-test="attachment"]').click();
await page.locator('[data-test="contact-submit"]').click();
await page.locator('[data-test="nav-sign-in"]').click();
await page.getByRole('heading', { name: 'Login' }).click();
await page.locator('[data-test="email"]').click();
await page.locator('[data-test="password"]').click();
await page.locator('[data-test="login-form"] button').click();
await page.locator('[data-test="login-form"] button').click();
await page.locator('[data-test="login-submit"]').click();
await page.locator('[data-test="register-link"]').click();
await page.locator('[data-test="forgot-password-link"]').click();

await page.getByRole('heading', { name: 'Forgot Password' }).click();
await page.locator('[data-test="email"]').click();
await page.locator('[data-test="forgot-password-submit"]').click();
await page.getByText('Email is required').click();

await page.locator('[data-test="register-link"]').click();
await page.getByRole('heading', { name: 'Customer registration' }).click();
await page.locator('[data-test="first-name"]').click();
await page.locator('[data-test="last-name"]').click();

await page.locator('[data-test="dob"]').fill('2025-06-11');

await page.locator('[data-test="postal_code"]').click();
await page.locator('[data-test="city"]').click();
await page.locator('[data-test="state"]').click();
await page.locator('[data-test="country"]').selectOption('IN');

await page.locator('[data-test="phone"]').click();
await page.locator('[data-test="email"]').click();
await page.locator('[data-test="password"]').click();
await page.getByRole('button').filter({ hasText: /^$/ }).click();

await page.locator('[data-test="register-submit"]').click();
await page.locator('[data-test="first-name-error"]').click();
await page.getByText('Last name is required').click();
await page.getByText('Street is required').click();
await page.getByText('Postcode is required').click();
await page.getByText('City is required').click();
await page.getByText('State is required').click();
await page.getByText('Phone is required.').click();
await page.getByText('Email is required').click();
await page.locator('[data-test="password-error"]').click();
await page.locator('[data-test="dob"]').press('ControlOrMeta+a');
await page.getByText('Date of Birth is required').click();

await page.locator('[data-test="lang-es"]').click();
await page.locator('[data-test="nav-sign-in"]').click();
await page.locator('[data-test="nav-home"]').click();
await page.locator('[data-test="language-select"]').click();
await page.getByRole('listitem').filter({ hasText: '»' }).click();
await page.getByRole('button', { name: 'Previous' }).click();
await page.locator('[data-test="page-title"]').click();
await page.locator('[data-test="nav-favorites"]').click();
await page.locator('[data-test="nav-profile"]').click();
await page.locator('[data-test="update-profile-submit"]').click();
await page.getByText('Your profile is successfully').click();
await page.locator('[data-test="nav-invoices"]').click();
await page.locator('[data-test="page-title"]').click();
await page.locator('[data-test="nav-messages"]').click();
await page.locator('[data-test="page-title"]').click();
await page.locator('[data-test="nav-cart"]').click();
await page.getByRole('cell', { name: 'Combination Pliers', exact: true }).click();
await page.getByRole('cell', { name: 'Quantity for Combination' }).click();
await page.getByRole('cell', { name: '$' }).first().click();
await page.getByRole('cell', { name: '$' }).nth(1).click();
await page.locator('tbody').getByRole('cell').filter({ hasText: /^$/ }).click();
await page.getByRole('cell', { name: 'Total' }).click();
await page.locator('[data-test="cart-total"]').click();
await page.locator('[data-test="proceed-1"]').click();
await page.locator('[data-test="proceed-2"]').click();
await page.locator('[data-test="proceed-3"]').click();
await page.locator('[data-test="payment-method"]').selectOption('bank-transfer');
await page.locator('[data-test="bank_name"]').click();
await page.locator('[data-test="account_name"]').click();
await page.locator('[data-test="account_number"]').click();
await page.locator('[data-test="finish"]').click();
await page.locator('[data-test="payment-method"]').selectOption('cash-on-delivery');
await page.locator('[data-test="payment-method"]').selectOption('credit-card');
await page.locator('[data-test="credit_card_number"]').click();
await page.locator('[data-test="expiration_date"]').click();
await page.locator('[data-test="cvv"]').click();
await page.locator('[data-test="card_holder_name"]').click();
await page.locator('[data-test="payment-method"]').selectOption('buy-now-pay-later');
await page.locator('[data-test="monthly_installments"]').selectOption('3');
await page.locator('[data-test="monthly_installments"]').selectOption('6');
await page.locator('[data-test="monthly_installments"]').selectOption('9');
await page.locator('[data-test="monthly_installments"]').selectOption('12');
await page.locator('[data-test="payment-method"]').selectOption('gift-card');
await page.locator('[data-test="gift_card_number"]').click();
await page.locator('[data-test="validation_code"]').click();
await page.locator('[data-test="finish"]').click();
await page.locator('[data-test="payment-method"]').selectOption('cash-on-delivery');
await page.locator('[data-test="finish"]').click();
await page.locator('[data-test="payment-success-message"]').click();
await page.locator('[data-test="finish"]').click();
await page.locator('[data-test="nav-home"]').click();
await page.locator('[data-test="nav-cart"]').click();
await page.getByRole('row', { name: 'Combination Pliers  Quantity' }).locator('a').click();
await page.locator('[data-test="nav-home"]').click();
await page.locator('[data-test="nav-categories"]').click();
*/